name: ec2-pipeline

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SECRET_KEY }}" > pradeepkey.pem
          chmod 400 pradeepkey.pem

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i pradeepkey.pem app.py ec2-user@13.233.127.9:/home/ec2-user/
          scp -o StrictHostKeyChecking=no -i pradeepkey.pem requirements.txt ec2-user@13.233.127.9:/home/ec2-user/

      - name: Deploy application on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i pradeepkey.pem ec2-user@13.233.127.9 << 'EOF'

          cd /home/ec2-user

          echo "Stopping old app..."
          pkill -f app.py || true

          echo "Installing dependencies..."
          pip3 install --user -r requirements.txt

          echo "Starting app..."
          nohup python3 app.py > app.log 2>&1 &

          echo "Deployment completed 🚀"
          EOF
