name: ec2-pipeline

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SECRET_KEY }}" > pradeepkey.pem
          chmod 400 pradeepkey.pem

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Copy project to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i pradeepkey.pem -r . ec2-user@13.233.127.9:/home/ec2-user/app

      - name: Deploy using Docker on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i pradeepkey.pem ec2-user@13.233.127.9 << 'EOF'

          cd /home/ec2-user/app

          echo "Stopping old container..."
          docker stop banking-app || true
          docker rm banking-app || true

          echo "Building Docker image..."
          docker build -t banking-app .

          echo "Running container..."
          docker run -d -p 5001:5001 --name banking-app banking-app

          echo "Deployment successful 🚀"
          EOF
